// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates.CommandBuilders
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class PostgresqlDeleteCommandBuilder : PostgresqlDeleteCommandBuilderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Text;
using System.Data.Common;
using System.Threading.Tasks;
using System.Linq.Expressions;
using System.Collections.Generic;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.CommandBuilders;
using Socigy.OpenSource.DB.Core.Interfaces;
using Socigy.OpenSource.DB.Core.Delegates;
using Socigy.OpenSource.DB.Core.Parsers;
using Socigy.OpenSource.DB.Core.Parsers.Postgresql;
using Npgsql;
using NpgsqlTypes;
using ");
            
            #line 20 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace Socigy.OpenSource.DB.CommandBuilders.Postgresql\r\n{\r\n    ");
            
            #line 24 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPreClass));
            
            #line default
            #line hidden
            this.Write("\r\n    public class Postgresql");
            
            #line 25 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("DeleteCommandBuilder<T> : SqlCommandBuilder<Postgresql");
            
            #line 25 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("DeleteCommandBuilder<T>>\r\n        where T : IDbTable\r\n    {\r\n#if NET6_0_OR_GREATE" +
                    "R\r\n        protected System.Data.Common.DbBatch? _Batch;\r\n\r\n        public Postg" +
                    "resql");
            
            #line 31 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("DeleteCommandBuilder<T> WithBatch(DbBatch? batch)\r\n        {\r\n            if (bat" +
                    "ch == null)\r\n            {\r\n                if (_Connection == null && _Transact" +
                    "ion == null)\r\n                    throw new ArgumentNullException(nameof(batch)," +
                    " \"If batch is null, either connection or transaction must be specified!\");\r\n\r\n  " +
                    "              _Batch = _Connection?.CreateBatch() ?? _Transaction!.Connection?.C" +
                    "reateBatch() ?? throw new InvalidOperationException(\"The provided transaction ha" +
                    "s no DbConnection from which a DbBatch could be created\");\r\n                _Bat" +
                    "ch.Transaction = _Transaction;\r\n            }\r\n            else\r\n               " +
                    " _Batch = batch;\r\n\r\n            return this;\r\n        }\r\n\r\n        public void A" +
                    "ddToBatch()\r\n        {\r\n            if (_Batch == null)\r\n                throw n" +
                    "ew InvalidOperationException(\"Cannot add to batch when no DbBatch was provided. " +
                    "Please call WithBatch() first.\");\r\n\r\n            var batchCommand = _Batch.Creat" +
                    "eBatchCommand();\r\n            _Batch.BatchCommands.Add(batchCommand);\r\n        }" +
                    "\r\n\r\n        public async Task AddToBatchAsync()\r\n        {\r\n            if (_Bat" +
                    "ch == null)\r\n                throw new InvalidOperationException(\"Cannot add to " +
                    "batch when no DbBatch was provided. Please call WithBatch() first.\");\r\n\r\n       " +
                    "     var batchCommand = _Batch.CreateBatchCommand();\r\n            _Batch.BatchCo" +
                    "mmands.Add(batchCommand);\r\n        }\r\n#endif\r\n\r\n        private readonly T? _Tab" +
                    "leRow;\r\n        private Expression<Func<T, bool>>? _WhereClause;\r\n\r\n        publ" +
                    "ic Postgresql");
            
            #line 69 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("DeleteCommandBuilder() { }\r\n        public Postgresql");
            
            #line 70 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("DeleteCommandBuilder(T rowInstance)\r\n        {\r\n            _TableRow = rowInstan" +
                    "ce;\r\n        }\r\n\r\n\r\n        public Postgresql");
            
            #line 76 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"DeleteCommandBuilder<T> Where(Expression<Func<T, bool>> where)
        {
            _WhereClause = where;
            return this;
        }

        private ISqlVisitor GetWhereVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
        {
            return new PostgresqlWhereVisitor(param, getColName, command);
        }

        public async Task<int> ExecuteAsync()
        {
#if NET6_0_OR_GREATER
            if (_Batch != null)
                throw new InvalidOperationException(""Cannot execute command when DbBatch was provided."");
#endif

            if (_Connection == null)
                throw new InvalidOperationException(""No DbConnection provided."");

            if (_Connection.State != System.Data.ConnectionState.Open)
                await _Connection.OpenAsync();

            await using var command = _Connection.CreateCommand() as NpgsqlCommand;
            if (command == null) return 0;

            if (_Transaction != null)
                command.Transaction = _Transaction as NpgsqlTransaction;

            string where = string.Empty;
            if (_WhereClause != null)
            {
                where = GetWhereVisitor(_WhereClause.Parameters[0], ");
            
            #line 109 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".GetColumnDbName, command).Parse(_WhereClause);
            }
            else if (_TableRow != null)
            {
                Dictionary<string, ColumnInfo> columns = _TableRow.GetPrimaryColumns();

                if (columns.Count == 0)
                    throw new InvalidOperationException(""No WHERE clause provided and the entity has no primary keys. Execution aborted to prevent deleting all rows in the table."");

                StringBuilder whereBuilder = new(""WHERE "");
                bool isFirst = true;

                foreach (var col in columns)
                {
                    if (!isFirst)
                        whereBuilder.Append("" AND "");

                    isFirst = false;

                    string colDbName = ");
            
            #line 128 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".GetColumnDbName(col.Key) ?? throw new InvalidDataException($""Invalid column mapping for key: {col.Key}"");
                    string paramName = $""@p{command.Parameters.Count}"";

                    whereBuilder.Append($""\""{colDbName}\"" = {paramName}"");

                    NpgsqlParameter param = new(paramName, GetDbType(col.Value.Type))
                    {
                        Value = col.Value.Value ?? DBNull.Value
                    };

                    command.Parameters.Add(param);
                }

                where = whereBuilder.ToString();
            }

            command.CommandText = $@""
        DELETE FROM """"{");
            
            #line 145 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".TableName}""""
        {where}"";

            return await command.ExecuteNonQueryAsync();
        }

        public NpgsqlDbType GetDbType(Type type)
        {
            type = Nullable.GetUnderlyingType(type) ?? type;

            return type switch
            {
                Type t when t == typeof(int) => NpgsqlDbType.Integer,
                Type t when t == typeof(long) => NpgsqlDbType.Bigint,
                Type t when t == typeof(string) => NpgsqlDbType.Text,
                Type t when t == typeof(bool) => NpgsqlDbType.Boolean,
                Type t when t == typeof(DateTime) => NpgsqlDbType.Timestamp,
                Type t when t == typeof(float) => NpgsqlDbType.Real,
                Type t when t == typeof(double) => NpgsqlDbType.Double,
                Type t when t == typeof(decimal) => NpgsqlDbType.Numeric,
                Type t when t == typeof(Guid) => NpgsqlDbType.Uuid,
                Type t when t == typeof(byte[]) => NpgsqlDbType.Bytea,
                Type t when t == typeof(short) => NpgsqlDbType.Smallint,
                Type t when t == typeof(char) => NpgsqlDbType.Char,
                _ => NpgsqlDbType.Text
            };
        }
    }
    ");
            
            #line 173 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPostClass));
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n\r\n#nullable disable\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 178 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlDeleteCommandBuilder.tt"

	public string ClassName { get; set; }
	public string Namespace { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class PostgresqlDeleteCommandBuilderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
