// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates.CommandBuilders
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlInsertCommandBuilder.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class PostgresqlInsertCommandBuilder : PostgresqlInsertCommandBuilderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Text;\r\nusing System.Data.Common;\r\nusing System.Thread" +
                    "ing.Tasks;\r\nusing System.Collections.Generic;\r\nusing Socigy.OpenSource.DB.Core;\r" +
                    "\nusing Socigy.OpenSource.DB.Core.CommandBuilders;\r\nusing Socigy.OpenSource.DB.Co" +
                    "re.Interfaces;\r\n\r\n#nullable enable\r\n\r\nnamespace Socigy.OpenSource.DB.CommandBuil" +
                    "ders.Postgresql\r\n{\r\n    public class PostgresqlInsertCommandBuilder<T> : SqlComm" +
                    "andBuilder<PostgresqlInsertCommandBuilder<T>>\r\n        where T : IDbTable\r\n    {" +
                    "\r\n#if NET6_0_OR_GREATER\r\n        protected System.Data.Common.DbBatch? _Batch;\r\n" +
                    "\r\n        /// <summary>\r\n        /// Specifies the batch to use for subsequent d" +
                    "atabase operations.\r\n        /// </summary>\r\n        /// <remarks>If <paramref n" +
                    "ame=\"batch\"/> is <see langword=\"null\"/>, the method attempts to create a new\r\n  " +
                    "      /// batch from the current connection or transaction. The batch is used to" +
                    " group multiple database commands for\r\n        /// execution as a single unit.</" +
                    "remarks>\r\n        /// <param name=\"batch\">The <see cref=\"DbBatch\"/> instance to " +
                    "associate with the operation, or <see langword=\"null\"/> to create a new\r\n       " +
                    " /// batch from the current connection or transaction.</param>\r\n        /// <ret" +
                    "urns>The current instance with the specified batch applied.</returns>\r\n        /" +
                    "// <exception cref=\"ArgumentNullException\">Thrown if <paramref name=\"batch\"/> is" +
                    " <see langword=\"null\"/> and neither a connection nor a transaction is\r\n        /" +
                    "// specified.</exception>\r\n        /// <exception cref=\"InvalidOperationExceptio" +
                    "n\">Thrown if <paramref name=\"batch\"/> is <see langword=\"null\"/> and the provided" +
                    " transaction does not have an\r\n        /// associated <see cref=\"DbConnection\"/>" +
                    ".</exception>\r\n        public PostgresqlInsertCommandBuilder<T> WithBatch(DbBatc" +
                    "h? batch)\r\n        {\r\n            if (batch == null)\r\n            {\r\n           " +
                    "     if (_Connection == null && _Transaction == null)\r\n                    throw" +
                    " new ArgumentNullException(nameof(batch), \"If batch is null, either connection o" +
                    "r transaction must be specified!\");\r\n\r\n                _Batch = _Connection?.Cre" +
                    "ateBatch() ?? _Transaction!.Connection?.CreateBatch() ?? throw new InvalidOperat" +
                    "ionException(\"The provided transaction has no DbConnection from which a DbBatch " +
                    "could be created\");\r\n                _Batch.Transaction = _Transaction;\r\n       " +
                    "     }\r\n            else\r\n                _Batch = batch;\r\n\r\n            return " +
                    "this;\r\n        }\r\n\r\n        /// <summary>\r\n        /// Adds a new command to the" +
                    " current batch operation.\r\n        /// </summary>\r\n        /// <remarks>This met" +
                    "hod should be called only after a batch has been initialized using\r\n        /// " +
                    "WithBatch(). Attempting to add to a batch without initialization will result in " +
                    "an exception.</remarks>\r\n        /// <exception cref=\"InvalidOperationException\"" +
                    ">Thrown if no batch has been provided. Call WithBatch() before invoking this met" +
                    "hod.</exception>\r\n        public void AddToBatch()\r\n        {\r\n            if (_" +
                    "Batch == null)\r\n                throw new InvalidOperationException(\"Cannot add " +
                    "to batch when no DbBatch was provided. Please call WithBatch() first.\");\r\n\r\n    " +
                    "        var batchCommand = _Batch.CreateBatchCommand();\r\n            _Batch.Batc" +
                    "hCommands.Add(batchCommand);\r\n        }\r\n\r\n        /// <summary>\r\n        /// Ad" +
                    "ds a new command to the current database batch asynchronously.\r\n        /// </su" +
                    "mmary>\r\n        /// <remarks>This method should be called only after a batch has" +
                    " been initialized using\r\n        /// WithBatch(). It is typically used to accumu" +
                    "late multiple commands for execution as a single batch\r\n        /// operation.</" +
                    "remarks>\r\n        /// <returns>A task that represents the asynchronous operation" +
                    ".</returns>\r\n        /// <exception cref=\"InvalidOperationException\">Thrown if n" +
                    "o database batch has been provided. Call WithBatch() before invoking this method" +
                    ".</exception>\r\n        public async Task AddToBatchAsync()\r\n        {\r\n         " +
                    "   if (_Batch == null)\r\n                throw new InvalidOperationException(\"Can" +
                    "not add to batch when no DbBatch was provided. Please call WithBatch() first.\");" +
                    "\r\n\r\n            var batchCommand = _Batch.CreateBatchCommand();\r\n            _Ba" +
                    "tch.BatchCommands.Add(batchCommand);\r\n        }\r\n#endif\r\n\r\n        private reado" +
                    "nly T _TableRow;\r\n        private Dictionary<string, ColumnInfo>? _ColumnInfo;\r\n" +
                    "\r\n        public PostgresqlInsertCommandBuilder(T rowInstance, Dictionary<string" +
                    ", ColumnInfo>? columnInfo = null)\r\n        {\r\n            _TableRow = rowInstanc" +
                    "e;\r\n            _ColumnInfo = columnInfo;\r\n        }\r\n\r\n        /// <summary>\r\n " +
                    "       /// Sets the column metadata to be used for building the PostgreSQL inser" +
                    "t command.\r\n        /// </summary>\r\n        /// <param name=\"columnInfo\">A dicti" +
                    "onary mapping column names to their associated metadata. Cannot be null.</param>" +
                    "\r\n        /// <returns>The current instance of <see cref=\"PostgresqlInsertComman" +
                    "dBuilder{T}\"/> with updated column information.</returns>\r\n        public Postgr" +
                    "esqlInsertCommandBuilder<T> WithColumnInfo(Dictionary<string, ColumnInfo> column" +
                    "Info)\r\n        {\r\n            _ColumnInfo = columnInfo;\r\n            return this" +
                    ";\r\n        }\r\n\r\n        // TODO: Implement ExecuteReturningAsync\r\n        public" +
                    " async Task<TReturning?> ExecuteReturningAsync<TReturning>()\r\n        {\r\n       " +
                    "     // TODO: Automatic Sequence value insertion\r\n            throw new NotImple" +
                    "mentedException();\r\n            return default;\r\n        }\r\n\r\n        // TODO: A" +
                    "utomatic Sequence value insertion\r\n        /// <summary>\r\n        /// Executes t" +
                    "he configured INSERT command asynchronously against the database connection.\r\n  " +
                    "      /// </summary>\r\n        /// <remarks>The method requires a valid and open " +
                    "database connection. If a transaction is\r\n        /// configured, the command wi" +
                    "ll execute within that transaction. Ensure that the connection and table row are" +
                    "\r\n        /// properly set up before calling this method.</remarks>\r\n        ///" +
                    " <returns>A task that represents the asynchronous operation. The task result is " +
                    "<see langword=\"true\"/> if one or more\r\n        /// rows were inserted; otherwise" +
                    ", <see langword=\"false\"/>.</returns>\r\n        /// <exception cref=\"InvalidOperat" +
                    "ionException\">Thrown if a batch operation is configured or if no database connec" +
                    "tion has been provided.</exception>\r\n        public async Task<bool> ExecuteAsyn" +
                    "c()\r\n        {\r\n#if NET6_0_OR_GREATER\r\n            if (_Batch != null)\r\n        " +
                    "        throw new InvalidOperationException(\"Cannot execute command, when DbBatc" +
                    "h was provided. Please call AddToBatchAsync()\");\r\n            else \r\n#endif\r\n   " +
                    "         if (_Connection == null)\r\n                throw new InvalidOperationExc" +
                    "eption(\"Cannot execute command, when no DbConnection was provided. Please call W" +
                    "ithConnection()/WithTransaction() first\");\r\n\r\n            if (_Connection.State " +
                    "!= System.Data.ConnectionState.Open)\r\n                await _Connection.OpenAsyn" +
                    "c();\r\n\r\n            var command = _Connection.CreateCommand();\r\n            if (" +
                    "_Transaction != null)\r\n                command.Transaction = _Transaction;\r\n\r\n  " +
                    "          // INSERT INTO {_TableRow.GetTableName()}(name1, name2, name3) VALUES(" +
                    "val1, val2, val3)\r\n\r\n            StringBuilder main = new($\"INSERT INTO \\\"{_Tabl" +
                    "eRow.GetTableName()}\\\"(\");\r\n            StringBuilder values = new();\r\n\r\n       " +
                    "     _ColumnInfo ??= _TableRow.GetColumns();\r\n            foreach (var row in _C" +
                    "olumnInfo)\r\n            {\r\n                main.Append($\"{row.Key}, \");\r\n\r\n     " +
                    "           // We don\'t need to worry about suplementing the value type to the Db" +
                    "Parameter\r\n                if (row.Value.Value == null || row.Value.Value == DBN" +
                    "ull.Value)\r\n                {\r\n                    values.AppendLine(\"NULL, \");\r" +
                    "\n                    continue;\r\n                }\r\n\r\n                var param =" +
                    " command.CreateParameter();\r\n                param.ParameterName = row.Key;\r\n   " +
                    "             param.Value = row.Value;\r\n                command.Parameters.Add(pa" +
                    "ram);\r\n\r\n                values.AppendLine($\"@{row.Key}, \");\r\n            }\r\n\r\n " +
                    "           command.CommandText = $\"{main.ToString().TrimEnd([\' \', \',\'])}) VALUES" +
                    "({values.ToString().TrimEnd([\' \', \',\'])})\";\r\n\r\n            int rowsAffected = aw" +
                    "ait command.ExecuteNonQueryAsync();\r\n            return rowsAffected > 0;\r\n     " +
                    "   }\r\n    }\r\n}\r\n\r\n#nullable disable\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class PostgresqlInsertCommandBuilderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
