// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates.CommandBuilders
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\CommandBuilders\PostgresqlInsertCommandBuilder.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class PostgresqlInsertCommandBuilder : PostgresqlInsertCommandBuilderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Text;\r\nusing System.Data.Common;\r\nusing System.Thread" +
                    "ing.Tasks;\r\nusing System.Collections.Generic;\r\nusing Socigy.OpenSource.DB.Core;\r" +
                    "\nusing Socigy.OpenSource.DB.Core.CommandBuilders;\r\nusing Socigy.OpenSource.DB.Co" +
                    "re.Interfaces;\r\nusing Npgsql;\r\nusing NpgsqlTypes;\r\n\r\n#nullable enable\r\n\r\nnamespa" +
                    "ce Socigy.OpenSource.DB.CommandBuilders.Postgresql\r\n{\r\n    public class Postgres" +
                    "qlInsertCommandBuilder<T> : SqlCommandBuilder<PostgresqlInsertCommandBuilder<T>>" +
                    "\r\n        where T : IDbTable\r\n    {\r\n#if NET6_0_OR_GREATER\r\n        protected Sy" +
                    "stem.Data.Common.DbBatch? _Batch;\r\n\r\n        /// <summary>\r\n        /// Specifie" +
                    "s the batch to use for subsequent database operations.\r\n        /// </summary>\r\n" +
                    "        /// <remarks>If <paramref name=\"batch\"/> is <see langword=\"null\"/>, the " +
                    "method attempts to create a new\r\n        /// batch from the current connection o" +
                    "r transaction. The batch is used to group multiple database commands for\r\n      " +
                    "  /// execution as a single unit.</remarks>\r\n        /// <param name=\"batch\">The" +
                    " <see cref=\"DbBatch\"/> instance to associate with the operation, or <see langwor" +
                    "d=\"null\"/> to create a new\r\n        /// batch from the current connection or tra" +
                    "nsaction.</param>\r\n        /// <returns>The current instance with the specified " +
                    "batch applied.</returns>\r\n        /// <exception cref=\"ArgumentNullException\">Th" +
                    "rown if <paramref name=\"batch\"/> is <see langword=\"null\"/> and neither a connect" +
                    "ion nor a transaction is\r\n        /// specified.</exception>\r\n        /// <excep" +
                    "tion cref=\"InvalidOperationException\">Thrown if <paramref name=\"batch\"/> is <see" +
                    " langword=\"null\"/> and the provided transaction does not have an\r\n        /// as" +
                    "sociated <see cref=\"DbConnection\"/>.</exception>\r\n        public PostgresqlInser" +
                    "tCommandBuilder<T> WithBatch(DbBatch? batch)\r\n        {\r\n            if (batch =" +
                    "= null)\r\n            {\r\n                if (_Connection == null && _Transaction " +
                    "== null)\r\n                    throw new ArgumentNullException(nameof(batch), \"If" +
                    " batch is null, either connection or transaction must be specified!\");\r\n\r\n      " +
                    "          _Batch = _Connection?.CreateBatch() ?? _Transaction!.Connection?.Creat" +
                    "eBatch() ?? throw new InvalidOperationException(\"The provided transaction has no" +
                    " DbConnection from which a DbBatch could be created\");\r\n                _Batch.T" +
                    "ransaction = _Transaction;\r\n            }\r\n            else\r\n                _Ba" +
                    "tch = batch;\r\n\r\n            return this;\r\n        }\r\n\r\n        /// <summary>\r\n  " +
                    "      /// Adds a new command to the current batch operation.\r\n        /// </summ" +
                    "ary>\r\n        /// <remarks>This method should be called only after a batch has b" +
                    "een initialized using\r\n        /// WithBatch(). Attempting to add to a batch wit" +
                    "hout initialization will result in an exception.</remarks>\r\n        /// <excepti" +
                    "on cref=\"InvalidOperationException\">Thrown if no batch has been provided. Call W" +
                    "ithBatch() before invoking this method.</exception>\r\n        public void AddToBa" +
                    "tch()\r\n        {\r\n            if (_Batch == null)\r\n                throw new Inv" +
                    "alidOperationException(\"Cannot add to batch when no DbBatch was provided. Please" +
                    " call WithBatch() first.\");\r\n\r\n            var batchCommand = _Batch.CreateBatch" +
                    "Command();\r\n            _Batch.BatchCommands.Add(batchCommand);\r\n        }\r\n\r\n  " +
                    "      /// <summary>\r\n        /// Adds a new command to the current database batc" +
                    "h asynchronously.\r\n        /// </summary>\r\n        /// <remarks>This method shou" +
                    "ld be called only after a batch has been initialized using\r\n        /// WithBatc" +
                    "h(). It is typically used to accumulate multiple commands for execution as a sin" +
                    "gle batch\r\n        /// operation.</remarks>\r\n        /// <returns>A task that re" +
                    "presents the asynchronous operation.</returns>\r\n        /// <exception cref=\"Inv" +
                    "alidOperationException\">Thrown if no database batch has been provided. Call With" +
                    "Batch() before invoking this method.</exception>\r\n        public async Task AddT" +
                    "oBatchAsync()\r\n        {\r\n            if (_Batch == null)\r\n                throw" +
                    " new InvalidOperationException(\"Cannot add to batch when no DbBatch was provided" +
                    ". Please call WithBatch() first.\");\r\n\r\n            var batchCommand = _Batch.Cre" +
                    "ateBatchCommand();\r\n            _Batch.BatchCommands.Add(batchCommand);\r\n       " +
                    " }\r\n#endif\r\n\r\n        private readonly T _TableRow;\r\n        private Dictionary<" +
                    "string, ColumnInfo>? _ColumnInfo;\r\n\r\n        public PostgresqlInsertCommandBuild" +
                    "er(T rowInstance, Dictionary<string, ColumnInfo>? columnInfo = null)\r\n        {\r" +
                    "\n            _TableRow = rowInstance;\r\n            _ColumnInfo = columnInfo;\r\n  " +
                    "      }\r\n\r\n        /// <summary>\r\n        /// Sets the column metadata to be use" +
                    "d for building the PostgreSQL insert command.\r\n        /// </summary>\r\n        /" +
                    "// <param name=\"columnInfo\">A dictionary mapping column names to their associate" +
                    "d metadata. Cannot be null.</param>\r\n        /// <returns>The current instance o" +
                    "f <see cref=\"PostgresqlInsertCommandBuilder{T}\"/> with updated column informatio" +
                    "n.</returns>\r\n        public PostgresqlInsertCommandBuilder<T> WithColumnInfo(Di" +
                    "ctionary<string, ColumnInfo> columnInfo)\r\n        {\r\n            _ColumnInfo = c" +
                    "olumnInfo;\r\n            return this;\r\n        }\r\n\r\n        // TODO: Implement Ex" +
                    "ecuteReturningAsync\r\n        public async Task<TReturning?> ExecuteReturningAsyn" +
                    "c<TReturning>()\r\n        {\r\n            // TODO: Automatic Sequence value insert" +
                    "ion\r\n            throw new NotImplementedException();\r\n            return defaul" +
                    "t;\r\n        }\r\n\r\n        // TODO: Automatic Sequence value insertion\r\n        //" +
                    "/ <summary>\r\n        /// Executes the configured INSERT command asynchronously a" +
                    "gainst the database connection.\r\n        /// </summary>\r\n        /// <remarks>Th" +
                    "e method requires a valid and open database connection. If a transaction is\r\n   " +
                    "     /// configured, the command will execute within that transaction. Ensure th" +
                    "at the connection and table row are\r\n        /// properly set up before calling " +
                    "this method.</remarks>\r\n        /// <returns>A task that represents the asynchro" +
                    "nous operation. The task result is <see langword=\"true\"/> if one or more\r\n      " +
                    "  /// rows were inserted; otherwise, <see langword=\"false\"/>.</returns>\r\n       " +
                    " /// <exception cref=\"InvalidOperationException\">Thrown if a batch operation is " +
                    "configured or if no database connection has been provided.</exception>\r\n        " +
                    "public async Task<bool> ExecuteAsync()\r\n        {\r\n#if NET6_0_OR_GREATER\r\n      " +
                    "      if (_Batch != null)\r\n                throw new InvalidOperationException(\"" +
                    "Cannot execute command when DbBatch was provided.\");\r\n#endif\r\n\r\n            if (" +
                    "_Connection == null)\r\n                throw new InvalidOperationException(\"No Db" +
                    "Connection provided.\");\r\n\r\n            if (_Connection.State != System.Data.Conn" +
                    "ectionState.Open)\r\n                await _Connection.OpenAsync();\r\n\r\n           " +
                    " await using var command = _Connection.CreateCommand() as NpgsqlCommand;\r\n      " +
                    "      if (command == null) return false;\r\n\r\n            if (_Transaction != null" +
                    ")\r\n                command.Transaction = _Transaction as NpgsqlTransaction;\r\n\r\n " +
                    "           _ColumnInfo ??= _TableRow.GetColumns();\r\n\r\n            var columnName" +
                    "s = new List<string>();\r\n            var paramNames = new List<string>();\r\n\r\n   " +
                    "         foreach (var row in _ColumnInfo)\r\n            {\r\n                string" +
                    " colName = row.Key;\r\n                object? value = row.Value.Value;\r\n         " +
                    "       Type type = row.Value.Type;\r\n\r\n                columnNames.Add($\"\\\"{colNa" +
                    "me}\\\"\");\r\n\r\n                string paramName = $\"@{colName}\";\r\n                p" +
                    "aramNames.Add(paramName);\r\n\r\n                var param = new NpgsqlParameter(par" +
                    "amName, value ?? DBNull.Value);\r\n\r\n                // If the value is null, we M" +
                    "UST specify the type explicitly\r\n                // If the value exists, Npgsql " +
                    "can usually infer it, but being explicit doesn\'t hurt.\r\n                if (valu" +
                    "e == null || value == DBNull.Value)\r\n                {\r\n                    para" +
                    "m.NpgsqlDbType = GetDbType(type);\r\n                }\r\n\r\n                command." +
                    "Parameters.Add(param);\r\n            }\r\n\r\n            command.CommandText = $@\"\r\n" +
                    "        INSERT INTO \"\"{_TableRow.GetTableName()}\"\" \r\n        ({string.Join(\", \"," +
                    " columnNames)}) \r\n        VALUES \r\n        ({string.Join(\", \", paramNames)})\";\r\n" +
                    "\r\n            int rowsAffected = await command.ExecuteNonQueryAsync();\r\n        " +
                    "    return rowsAffected > 0;\r\n        }\r\n\r\n        public NpgsqlDbType GetDbType" +
                    "(Type type)\r\n        {\r\n            type = Nullable.GetUnderlyingType(type) ?? t" +
                    "ype;\r\n\r\n            return type switch\r\n            {\r\n                Type t wh" +
                    "en t == typeof(int) => NpgsqlDbType.Integer,\r\n                Type t when t == t" +
                    "ypeof(long) => NpgsqlDbType.Bigint,\r\n                Type t when t == typeof(str" +
                    "ing) => NpgsqlDbType.Text,\r\n                Type t when t == typeof(bool) => Npg" +
                    "sqlDbType.Boolean,\r\n                Type t when t == typeof(DateTime) => NpgsqlD" +
                    "bType.Timestamp,\r\n                Type t when t == typeof(float) => NpgsqlDbType" +
                    ".Real,\r\n                Type t when t == typeof(double) => NpgsqlDbType.Double,\r" +
                    "\n                Type t when t == typeof(decimal) => NpgsqlDbType.Numeric,\r\n    " +
                    "            Type t when t == typeof(Guid) => NpgsqlDbType.Uuid,\r\n               " +
                    " Type t when t == typeof(byte[]) => NpgsqlDbType.Bytea,\r\n                Type t " +
                    "when t == typeof(short) => NpgsqlDbType.Smallint,\r\n                Type t when t" +
                    " == typeof(char) => NpgsqlDbType.Char,\r\n                // Fallback or specific " +
                    "handling for JSON, Arrays, etc.\r\n                _ => NpgsqlDbType.Text\r\n       " +
                    "     };\r\n        }\r\n    }\r\n}\r\n\r\n#nullable disable\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class PostgresqlInsertCommandBuilderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
