// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class MigrationManagerTemplate : MigrationManagerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Microsoft.Extensions.DependencyInjection;\r\nusing Microsoft.Extensions.Loggi" +
                    "ng;\r\nusing Socigy.OpenSource.DB.Core.Migrations;\r\nusing Socigy.OpenSource.DB.Cor" +
                    "e;\r\nusing Socigy.OpenSource.DB.Migrations;\r\n\r\n#nullable enable\r\n\r\nnamespace ");
            
            #line 14 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public static partial class ");
            
            #line 16 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public class MigrationManager : IMigrationManager\r\n        {\r\n  " +
                    "          private static readonly List<ILocalMigration> _localMigrationsOrderedD" +
                    "esc =\r\n            [\r\n    ");
            
            #line 22 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"

                foreach (var migrationName in MigrationClassNames) 
                {
    
            
            #line default
            #line hidden
            this.Write("          new ");
            
            #line 25 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(migrationName));
            
            #line default
            #line hidden
            this.Write("(),\r\n    ");
            
            #line 26 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"

                }
    
            
            #line default
            #line hidden
            this.Write(@"            ];

            private Dictionary<string, ILocalMigration> _localMigrations = _localMigrationsOrderedDesc.ToDictionary(static x => x.Id, static x => x);
            public Dictionary<string, ILocalMigration> LocalMigrations => _localMigrations;


            private readonly ILogger _Logger;
            private readonly IDbConnectionFactory _ConnectionFactory;
            public MigrationManager(ILogger<MigrationManager> logger, [FromKeyedServices(""");
            
            #line 37 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write("\")] IDbConnectionFactory connectionFactory)\r\n            {\r\n                _Logg" +
                    "er = logger;\r\n                _ConnectionFactory = connectionFactory;\r\n         " +
                    "   }\r\n\r\n            public Task EnsureLatestVersion()\r\n            {\r\n          " +
                    "      return EnsureMigration(_localMigrationsOrderedDesc.First());\r\n            " +
                    "}\r\n            public Task EnsureMigration(string migrationId)\r\n            {\r\n " +
                    "               if (!_localMigrations.TryGetValue(migrationId, out ILocalMigratio" +
                    "n? migration))\r\n                    throw new MissingMemberException($\"Missing l" +
                    "ocal migration with ID {migrationId}\"); \r\n\r\n                return EnsureMigrati" +
                    "on(migration);\r\n            }\r\n            public async Task EnsureMigration(ILo" +
                    "calMigration migration)\r\n            {\r\n                await _ConnectionFactory" +
                    ".EnsureDbExists();\r\n\r\n                var dbVersion = await GetCurrentMigrationV" +
                    "ersion();\r\n                int sourceMigrationIndex = -1;\r\n                int t" +
                    "argetMigrationIndex = -1;\r\n\r\n                if (dbVersion == null)\r\n           " +
                    "         sourceMigrationIndex = _localMigrationsOrderedDesc.Count;\r\n            " +
                    "    else \r\n                {\r\n                    sourceMigrationIndex = _localM" +
                    "igrationsOrderedDesc.FindIndex(x => x.Id == dbVersion.HumanId);\r\n               " +
                    "     if (sourceMigrationIndex < 0)\r\n                    {\r\n                     " +
                    "   throw new InvalidDataException($\"Unable to find local migration with ID {dbVe" +
                    "rsion.HumanId} that is in the Database. Aborting!\");\r\n                    }\r\n   " +
                    "             }\r\n\r\n                targetMigrationIndex = _localMigrationsOrdered" +
                    "Desc.FindIndex(x => x.Id == migration.Id);\r\n                if (targetMigrationI" +
                    "ndex < 0) throw new InvalidDataException($\"Target migration {migration.Id} not f" +
                    "ound locally.\");\r\n\r\n\r\n                if (sourceMigrationIndex == targetMigratio" +
                    "nIndex)\r\n                {\r\n                    _Logger.LogInformation($\"");
            
            #line 79 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write(@" is already at version: {migration.Id}"");
                    return;
                }

                using var connection = _ConnectionFactory.Create();
                await connection.OpenAsync();

                if (sourceMigrationIndex > targetMigrationIndex)
                {
                    for (int i = sourceMigrationIndex - 1; i >= targetMigrationIndex; i--)
                    {
                        var migToApply = _localMigrationsOrderedDesc[i];
                        _Logger.LogInformation($""Applying UP migration: {migToApply.Id} - {migToApply.GetType().Name}"");

                        using var command = connection.CreateCommand();
                        command.CommandText = migToApply.UpSql;
                        await command.ExecuteNonQueryAsync();

                        // Record the migration
                        await ");
            
            #line 98 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write(".Migration.InsertAsync(new ");
            
            #line 98 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write(@".Migration
                        {
                            HumanId = migToApply.Id,
                            AppliedAt = DateTime.UtcNow,
                            ExecutedBy = $""{Environment.UserName} - {Environment.MachineName}"",
                            IsRollback = false
                        }, connection);
                    }
                }
                else
                {
                    for (int i = sourceMigrationIndex; i < targetMigrationIndex; i++)
                    {
                        var migToApply = _localMigrationsOrderedDesc[i];
                        _Logger.LogInformation($""Applying DOWN migration: {migToApply.Id} - {migToApply.GetType().Name}"");

                        using var command = connection.CreateCommand();
                        command.CommandText = migToApply.DownSql;
                        await command.ExecuteNonQueryAsync();

                        // Record the rollback
                        await ");
            
            #line 119 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write(".Migration.InsertAsync(new ");
            
            #line 119 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write(@".Migration
                        {
                            HumanId = migToApply.Id,
                            AppliedAt = DateTime.UtcNow,
                            ExecutedBy = $""{Environment.UserName} - {Environment.MachineName}"",
                            IsRollback = true
                        }, connection);
                    }
                }
            }

            public async Task<ILocalMigration?> GetCurrentLocalMigrationVersion()
            {
                var latestVersion = await GetCurrentMigrationVersion();
                if (latestVersion == null || !_localMigrations.TryGetValue(latestVersion.HumanId, out var result))
                    return null;

                return result;
            }

            public async Task<IMigration?> GetCurrentMigrationVersion()
            {
                try 
                {
                    using var connection = _ConnectionFactory.Create();

                    var versions = ");
            
            #line 145 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseName));
            
            #line default
            #line hidden
            this.Write(@".Migration.Query()
                        .WithConnection(connection)
                        .OrderByDesc(x => new object[] { x.AppliedAt })
                        .ExecuteAsync();

                    return await versions.FirstAsync();
                }
                catch (Exception ex)
                {
                    return null;
                }
            }
        }
    }
}

#nullable disable

");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 163 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\MigrationManagerTemplate.tt"

    public string DatabaseName { get; set; }
    public string BaseNamespace { get; set; }
    public IList<string> MigrationClassNames { get; set; } = [];

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class MigrationManagerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
