// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class TableSyntaxGeneratorTemplate : TableSyntaxGeneratorTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
// Auto-generated code. Do not modify manually. Socigy.OpenSource.DB Source Generator

using System.Data.Common;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Collections.Generic;
using Socigy.OpenSource.DB.Core.Convertors;
using Socigy.OpenSource.DB.Core.Parsers;
using Socigy.OpenSource.DB.Core.Parsers.");
            
            #line 15 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write(";\r\nusing Socigy.OpenSource.DB.Core.Delegates;\r\n\r\nnamespace ");
            
            #line 18 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic partial class ");
            
            #line 20 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n        public static TableQueryBuilder Query(Expression<Func<");
            
            #line 22 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", bool>> where)
        {
            return new TableQueryBuilder().Where(where);
        }

        public static TableQueryBuilder Query()
        {
            return new TableQueryBuilder();
        }

        #region Object <-> DB Conversion
        public T? ReadValue<T>(DbDataReader reader, string columnName, Dictionary<string, string>? columnOverrides = null)
        {
            int index = GetColumnDbIndex(reader, columnName, columnOverrides);
            if (index < 0 || reader.IsDBNull(index))
                return default;

            return (T)reader.GetValue(index);
        }

        public T? ReadValueConvertor<T, TConvertor>(DbDataReader reader, int index)
            where TConvertor : IDbValueConvertor<T>, new()
        {
            if (index < 0 || reader.IsDBNull(index))
                return default;

            var convertor = new TConvertor();
            return convertor.ConvertFromDbValue(reader.GetValue(index));
        }

        public int GetColumnDbIndex(DbDataReader reader, string columnName, Dictionary<string, string>? columnOverrides = null)
        {
            if (columnOverrides != null && columnOverrides.ContainsKey(columnName))
                columnName = columnOverrides[columnName];

            return reader.GetOrdinal(columnName);
        }

        public ");
            
            #line 60 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("() {}\r\n        public ");
            
            #line 61 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(DbDataReader reader, Dictionary<string, string>? columnOverrides = null)\r\n      " +
                    "  {\r\n        ");
            
            #line 63 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

            foreach(var column in Columns) 
            {
                if (string.IsNullOrEmpty(column.Converter))
                {


            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 69 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write(" = ReadValue<");
            
            #line 69 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.TypeName));
            
            #line default
            #line hidden
            this.Write(">(reader, \"");
            
            #line 69 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write("\", columnOverrides);\r\n");
            
            #line 70 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write(" = ReadValueConvertor<");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.TypeName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Converter));
            
            #line default
            #line hidden
            this.Write(">(reader, \"");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write("\", columnOverrides);\r\n");
            
            #line 75 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

                }
            }
        
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public static ");
            
            #line 81 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ConvertFrom(DbDataReader reader, Dictionary<string, string>? columnOverrides = n" +
                    "ull)\r\n        {\r\n            return new ");
            
            #line 83 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"(reader, columnOverrides);
        }
        #endregion

        public static Task<bool> InsertAsync()
        {
            // TODO: Implement conversion logic
            throw new NotImplementedException();
        }
        public static Task<T?> InsertAsyncReturning<T>()
        {
            // TODO: Implement conversion logic
            throw new NotImplementedException();
        }

        public static async Task<int> UpdateAsync()
        {
            // TODO: Implement conversion logic
            throw new NotImplementedException();
        }

        public static async Task<bool> DeleteAsync()
        {
            // TODO: Implement conversion logic
            throw new NotImplementedException();
        }

        public struct TableQueryBuilder
        {
            private DbConnection? _Connection;
            private DbTransaction? _Transaction;
            private DbBatch? _Batch;

            private Expression<Func<");
            
            #line 116 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", object?[]>> _SelectClause;\r\n            private Expression<Func<");
            
            #line 117 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", bool>> _WhereClause;\r\n\r\n            private Expression<Func<");
            
            #line 119 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", object?[]>>? _OrderByClause;\r\n            private bool _OrderByDescending = fal" +
                    "se;\r\n\r\n            private int _Limit = -1;\r\n            private int _Offset = -" +
                    "1;\r\n\r\n            public TableQueryBuilder()\r\n            {\r\n            }\r\n\r\n  " +
                    "          /// <summary>\r\n            /// Associates the specified database trans" +
                    "action with the query builder instance. Use this or <see cref=\"WithConnection(Db" +
                    "Connection)\"/> to specify the context for query execution.\r\n            /// </su" +
                    "mmary>\r\n            /// <remarks>Use this method to ensure that all queries exec" +
                    "uted by this builder participate in\r\n            /// the provided transaction. T" +
                    "his is useful for maintaining atomicity across multiple operations.</remarks>\r\n " +
                    "           /// <exception cref=\"ArgumentNullException\">Thrown if the provided <p" +
                    "aramref name=\"transaction\"/> is null.</exception>\r\n            /// <exception cr" +
                    "ef=\"ArgumentException\">Thrown if the provided <paramref name=\"transaction\"/> has" +
                    " no associated DbConnection.</exception>\r\n            /// <param name=\"transacti" +
                    "on\">The database transaction to use for subsequent query operations. Cannot be n" +
                    "ull.</param>\r\n            /// <returns>The current <see cref=\"TableQueryBuilder\"" +
                    "/> instance with the transaction applied.</returns>\r\n            public TableQue" +
                    "ryBuilder WithTransaction(DbTransaction transaction)\r\n            {\r\n           " +
                    "     _Transaction = transaction;\r\n                if (_Transaction == null)\r\n   " +
                    "                 throw new ArgumentNullException(nameof(transaction));\r\n        " +
                    "        else if (_Transaction.Connection == null)\r\n                    throw new" +
                    " ArgumentException(\"The provided transaction has no associated DbConnection.\", n" +
                    "ameof(transaction));\r\n\r\n                _Connection = _Transaction.Connection;\r\n" +
                    "\r\n                return this;\r\n            }\r\n\r\n            /// <summary>\r\n    " +
                    "        /// Sets the database connection to be used for subsequent queries and r" +
                    "eturns the current builder instance. Use this or <see cref=\"WithTransaction(DbTr" +
                    "ansaction)\"/> to specify the context for query execution.\"/>\r\n            /// </" +
                    "summary>\r\n            /// <remarks>This method enables fluent configuration of t" +
                    "he query builder. The provided\r\n            /// connection will be used for all " +
                    "future query operations performed by this instance.</remarks>\r\n            /// <" +
                    "exception cref=\"ArgumentNullException\">Thrown if the provided <paramref name=\"co" +
                    "nnection\"/> is null.</exception>\r\n            /// <param name=\"connection\">The d" +
                    "atabase connection to associate with the query builder. Cannot be null.</param>\r" +
                    "\n            /// <returns>The current <see cref=\"TableQueryBuilder\"/> instance w" +
                    "ith the specified connection set.</returns>\r\n            public TableQueryBuilde" +
                    "r WithConnection(DbConnection connection)\r\n            {\r\n                _Conne" +
                    "ction = connection;\r\n                if (_Connection == null)\r\n                 " +
                    "   throw new ArgumentNullException(nameof(connection));\r\n\r\n                retur" +
                    "n this;\r\n            }\r\n\r\n            /// <summary>\r\n            /// Associates " +
                    "the specified database batch operation with the query builder, enabling batched " +
                    "execution of user\r\n            /// table queries.\r\n            /// </summary>\r\n " +
                    "           /// <remarks>Use this method to execute multiple queries as part of a" +
                    " single batch operation. This\r\n            /// can improve performance and ensur" +
                    "e atomicity when supported by the underlying database.</remarks>\r\n            //" +
                    "/ <exception cref=\"ArgumentNullException\">Thrown if the provided <paramref name=" +
                    "\"batch\"/> is null and Connection/Transaction was not set.</exception>\r\n         " +
                    "   /// <param name=\"batch\">The database batch to use for executing queries. If n" +
                    "ull the connection/transaction must be specified!</param>\r\n            /// <retu" +
                    "rns>The current <see cref=\"TableQueryBuilder\"/> instance with the batch operatio" +
                    "n applied.</returns>\r\n            public TableQueryBuilder WithBatch(DbBatch? ba" +
                    "tch)\r\n            {\r\n                if (batch == null)\r\n                {\r\n    " +
                    "                if (_Connection == null && _Transaction == null)\r\n              " +
                    "          throw new ArgumentNullException(nameof(batch), \"If batch is null, eith" +
                    "er connection or transaction must be specified!\");\r\n\r\n                    _Batch" +
                    " = _Connection?.CreateBatch() ?? _Transaction!.Connection?.CreateBatch() ?? thro" +
                    "w new InvalidOperationException(\"The provided transaction has no DbConnection fr" +
                    "om which a DbBatch could be created\");\r\n                    _Batch.Transaction =" +
                    " _Transaction;\r\n                }\r\n                else\r\n                    _Ba" +
                    "tch = batch;\r\n\r\n                return this;\r\n            }\r\n\r\n            /// <" +
                    "summary>\r\n            /// Specifies the columns to select when querying the user" +
                    " table.\r\n            /// </summary>\r\n            /// <remarks>If not called, all" +
                    " columns will be selected by default. This method allows for\r\n            /// pr" +
                    "ojection of only the desired columns, which can improve query performance and re" +
                    "duce data\r\n            /// transfer.</remarks>\r\n            /// <param name=\"sel" +
                    "ect\">An expression that defines which properties of the <see cref=\"");
            
            #line 199 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> entity to include in the result set.
            /// The expression should return an array of selected property values.</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance, enabling method chaining.</returns>
            public TableQueryBuilder Select(Expression<Func<");
            
            #line 202 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", object?[]>> select)
            {
                _SelectClause = select;
                return this;
            }

            /// <summary>
            /// Adds a filter condition to the query that determines which users are included based on the specified
            /// predicate.
            /// </summary>
            /// <remarks>Only one filter condition can be set per query builder instance; subsequent calls to
            /// <c>Where</c> will overwrite the previous condition.</remarks>
            /// <param name=""where"">An expression that defines the criteria used to select users. The predicate should return <see
            /// langword=""true""/> for users to include in the results.</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance, enabling method chaining for additional query
            /// configuration.</returns>
            public TableQueryBuilder Where(Expression<Func<");
            
            #line 218 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", bool>> where)\r\n            {\r\n                _WhereClause = where;\r\n          " +
                    "      return this;\r\n            }\r\n\r\n            /// <summary>\r\n            /// " +
                    "Sets the maximum number of user records to return in the query results.\r\n       " +
                    "     /// </summary>\r\n            /// <param name=\"limit\">The maximum number of u" +
                    "ser records to include in the result set. Must be zero or a positive integer.</p" +
                    "aram>\r\n            /// <exception cref=\"ArgumentOutOfRangeException\">Thrown if t" +
                    "he provided <paramref name=\"limit\"/> is negative.</exception>\r\n            /// <" +
                    "returns>The current <see cref=\"TableQueryBuilder\"/> instance with the limit appl" +
                    "ied.</returns>\r\n            public TableQueryBuilder Limit(int limit)\r\n         " +
                    "   {\r\n                ArgumentOutOfRangeException.ThrowIfNegative(limit);\r\n\r\n   " +
                    "             _Limit = limit;\r\n                return this;\r\n            }\r\n\r\n   " +
                    "         /// <summary>\r\n            /// Sets the number of rows to skip before s" +
                    "tarting to return results from the query.\r\n            /// </summary>\r\n         " +
                    "   /// <remarks>Use this method to implement paging in query results. Calling th" +
                    "is method overwrites\r\n            /// any previously set offset value.</remarks>" +
                    "\r\n            /// <exception cref=\"ArgumentOutOfRangeException\">Thrown if the pr" +
                    "ovided <paramref name=\"offset\"/> is negative.</exception>\r\n            /// <para" +
                    "m name=\"offset\">The number of rows to skip. Must be zero or greater.</param>\r\n  " +
                    "          /// <returns>The current <see cref=\"TableQueryBuilder\"/> instance with" +
                    " the offset applied.</returns>\r\n            public TableQueryBuilder Offset(int " +
                    "offset)\r\n            {\r\n                ArgumentOutOfRangeException.ThrowIfNegat" +
                    "ive(offset);\r\n\r\n                _Offset = offset;\r\n                return this;\r" +
                    "\n            }\r\n\r\n            /// <summary>\r\n            /// Limits the number o" +
                    "f rows returned by the query to the specified maximum.\r\n            /// </summar" +
                    "y>\r\n            /// <remarks>Use this method to restrict the result set to a spe" +
                    "cific number of rows, similar to\r\n            /// the SQL TOP clause. Calling th" +
                    "is method overrides any previous row limit set on the query.</remarks>\r\n        " +
                    "    /// <param name=\"top\">The maximum number of rows to return. Must be greater " +
                    "than zero.</param>\r\n            /// <returns>The current <see cref=\"TableQueryBu" +
                    "ilder\"/> instance with the row limit applied.</returns>\r\n            public Tabl" +
                    "eQueryBuilder Top(int top)\r\n            {\r\n                return Limit(top);\r\n " +
                    "           }\r\n\r\n            /// <summary>\r\n            /// Specifies the orderin" +
                    "g of results for the query using the provided expression.\r\n            /// </sum" +
                    "mary>\r\n            /// <remarks>If multiple properties are specified in the arra" +
                    "y, results will be ordered by each\r\n            /// property in the order they a" +
                    "ppear. This method can be chained with other query builder methods to construct\r" +
                    "\n            /// complex queries.</remarks>\r\n            /// <param name=\"clause" +
                    "\">An expression that defines one or more properties of the <see cref=\"");
            
            #line 272 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> entity to order the results by.
            /// The array elements determine the order of precedence. You can use <see cref=""DB.OrderBy""/> for complex ordering (default will be ASC)</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance with the ordering clause applied.</returns>
            public TableQueryBuilder OrderBy(Expression<Func<");
            
            #line 275 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", object?[]>> clause)
            {
                _OrderByClause = clause;
                return this;
            }

            /// <summary>
            /// Specifies a descending order for the query results based on the provided user properties.
            /// </summary>
            /// <remarks>Call this method to order the query results by one or more user properties in
            /// descending order. This method can be chained with other query builder methods to construct complex
            /// queries.</remarks>
            /// <param name=""clause"">An expression that selects one or more properties of the <see cref=""");
            
            #line 287 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> entity to use for ordering the
            /// results in descending order. You can use <see cref=""DB.OrderBy""/> for complex ordering (default will be DESC)</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance to allow method chaining.</returns>
            public TableQueryBuilder OrderByDesc(Expression<Func<");
            
            #line 290 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", object?[]>> clause)\r\n            {\r\n                _OrderByClause = clause;\r\n " +
                    "               _OrderByDescending = true;\r\n                return this;\r\n       " +
                    "     }\r\n\r\n            /// <summary>\r\n            /// Adds a new command to the c" +
                    "urrent batch operation.\r\n            /// </summary>\r\n            /// <remarks>Th" +
                    "is method should be called only after a batch has been initialized using\r\n      " +
                    "      /// WithBatch(). Attempting to add to a batch without initialization will " +
                    "result in an exception.</remarks>\r\n            /// <exception cref=\"InvalidOpera" +
                    "tionException\">Thrown if no batch has been provided. Call WithBatch() before inv" +
                    "oking this method.</exception>\r\n            public void AddToBatch()\r\n          " +
                    "  {\r\n                if (_Batch == null)\r\n                    throw new InvalidO" +
                    "perationException(\"Cannot add to batch when no DbBatch was provided. Please call" +
                    " WithBatch() first.\");\r\n\r\n                var batchCommand = _Batch.CreateBatchC" +
                    "ommand();\r\n                _Batch.BatchCommands.Add(batchCommand);\r\n            " +
                    "}\r\n\r\n            /// <summary>\r\n            /// Adds a new command to the curren" +
                    "t database batch asynchronously.\r\n            /// </summary>\r\n            /// <r" +
                    "emarks>This method should be called only after a batch has been initialized usin" +
                    "g\r\n            /// WithBatch(). It is typically used to accumulate multiple comm" +
                    "ands for execution as a single batch\r\n            /// operation.</remarks>\r\n    " +
                    "        /// <returns>A task that represents the asynchronous operation.</returns" +
                    ">\r\n            /// <exception cref=\"InvalidOperationException\">Thrown if no data" +
                    "base batch has been provided. Call WithBatch() before invoking this method.</exc" +
                    "eption>\r\n            public async Task AddToBatchAsync()\r\n            {\r\n       " +
                    "         if (_Batch == null)\r\n                    throw new InvalidOperationExce" +
                    "ption(\"Cannot add to batch when no DbBatch was provided. Please call WithBatch()" +
                    " first.\");\r\n\r\n                var batchCommand = _Batch.CreateBatchCommand();\r\n " +
                    "               _Batch.BatchCommands.Add(batchCommand);\r\n            }\r\n\r\n       " +
                    "     private ISqlVisitor GetSelectVisitor(ParameterExpression param, GetColumnNa" +
                    "me getColName, DbCommand command)\r\n            {\r\n                return new ");
            
            #line 331 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("SelectVisitor(param, getColName, command);\r\n            }\r\n\r\n            private " +
                    "ISqlVisitor GetWhereVisitor(ParameterExpression param, GetColumnName getColName," +
                    " DbCommand command)\r\n            {\r\n                return new ");
            
            #line 336 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("WhereVisitor(param, getColName, command);\r\n            }\r\n\r\n            private I" +
                    "SqlVisitor GetOrderByVisitor(ParameterExpression param, GetColumnName getColName" +
                    ", DbCommand command, bool orderByDesc)\r\n            {\r\n                return ne" +
                    "w ");
            
            #line 341 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("OrderByVisitor(param, getColName, command, orderByDesc);\r\n            }\r\n\r\n      " +
                    "      public async IAsyncEnumerable<");
            
            #line 344 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"> ExecuteAsync()
            {
                if (_Batch != null)
                    throw new InvalidOperationException(""Cannot execute command, when DbBatch was provided. Please call AddToBatchAsync()"");
                else if (_Connection == null)
                    throw new InvalidOperationException(""Cannot execute command, when no DbConnection was provided. Please call WithConnection()/WithTransaction() first"");

                if (_Connection.State != System.Data.ConnectionState.Open)
                    await _Connection.OpenAsync();

                var command = _Connection.CreateCommand();

                Stopwatch watch = Stopwatch.StartNew();
                var parser = new SqlQueryBuilderExpressionParser<");
            
            #line 357 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">(command, ");
            
            #line 357 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".GetColumnDbName, GetSelectVisitor, GetWhereVisitor, GetOrderByVisitor);\r\n       " +
                    "         parser.Process(");
            
            #line 358 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".TableName, _SelectClause, _WhereClause, _OrderByClause, _OrderByDescending);
                if (_Limit > 0)
                    parser.AddLimit(_Limit);
                if (_Offset > 0)
                    parser.AddOffset(_Offset);

                command.CommandText = parser.ToString();

                Console.WriteLine($""[TableQueryBuilder] Executing SQL Query: {command.CommandText} (Prepared in {watch.ElapsedMilliseconds} ms)"");

                using var reader = await command.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    yield return ");
            
            #line 371 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".ConvertFrom(reader);\r\n                }\r\n            }\r\n        }\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 378 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

	public string Namespace { get; set; }
	public string ClassName { get; set; }
    public string DbEnginePrefix { get; set; }

    #nullable enable
    public IList<(string SourceName, string TypeName, string? Converter)> Columns { get; set; } = [];
    #nullable disable

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class TableSyntaxGeneratorTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
