// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Socigy.OpenSource.DB.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class TableSyntaxGeneratorTemplate : TableSyntaxGeneratorTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
// Auto-generated code. Do not modify manually. Socigy.OpenSource.DB Source Generator

using System.Data.Common;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Collections.Generic;
using Socigy.OpenSource.DB.Core;
using Socigy.OpenSource.DB.Core.Convertors;
using Socigy.OpenSource.DB.Core.Parsers;
using Socigy.OpenSource.DB.Core.Parsers.");
            
            #line 16 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write(";\r\nusing Socigy.OpenSource.DB.Core.Delegates;\r\nusing Socigy.OpenSource.DB.Command" +
                    "Builders.");
            
            #line 18 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n#nullable enable\r\n\r\nnamespace ");
            
            #line 22 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    ");
            
            #line 24 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPreClass));
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic partial class ");
            
            #line 25 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n        public static TableQueryBuilder Query(Expression<Func<");
            
            #line 27 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", bool>> where)
        {
            return new TableQueryBuilder().Where(where);
        }

        public static TableQueryBuilder Query()
        {
            return new TableQueryBuilder();
        }

        #region Object <-> DB Conversion
        public T? ReadValue<T>(DbDataReader reader, string columnName, Dictionary<string, string>? columnOverrides = null)
        {
            int index = GetColumnDbIndex(reader, columnName, columnOverrides);
            if (index < 0 || reader.IsDBNull(index))
                return default;

            return (T)reader.GetValue(index);
        }

        public T? ReadValueConvertor<T, TConvertor>(DbDataReader reader, int index)
            where TConvertor : IDbValueConvertor<T>, new()
        {
            if (index < 0 || reader.IsDBNull(index))
                return default;

            var convertor = new TConvertor();
            return convertor.ConvertFromDbValue(reader.GetValue(index));
        }

        public int GetColumnDbIndex(DbDataReader reader, string columnName, Dictionary<string, string>? columnOverrides = null)
        {
            if (columnOverrides != null && columnOverrides.ContainsKey(columnName))
                columnName = columnOverrides[columnName];

            return reader.GetOrdinal(columnName);
        }

        public ");
            
            #line 65 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("() {}\r\n        public ");
            
            #line 66 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(DbDataReader reader, Dictionary<string, string>? columnOverrides = null)\r\n      " +
                    "  {\r\n        ");
            
            #line 68 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

            foreach(var column in Columns) 
            {
                if (string.IsNullOrEmpty(column.Converter))
                {


            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write(" = ReadValue<");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.TypeName));
            
            #line default
            #line hidden
            this.Write(">(reader, ");
            
            #line 74 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write("ColumnName, columnOverrides);\r\n");
            
            #line 75 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

                }
                else
                {

            
            #line default
            #line hidden
            this.Write("          ");
            
            #line 79 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write(" = ReadValueConvertor<");
            
            #line 79 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.TypeName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 79 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Converter));
            
            #line default
            #line hidden
            this.Write(">(reader, ");
            
            #line 79 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.SourceName));
            
            #line default
            #line hidden
            this.Write("ColumnName, columnOverrides);\r\n");
            
            #line 80 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

                }
            }
        
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public static ");
            
            #line 86 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ConvertFrom(DbDataReader reader, Dictionary<string, string>? columnOverrides = n" +
                    "ull)\r\n        {\r\n            return new ");
            
            #line 88 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(reader, columnOverrides);\r\n        }\r\n        #endregion\r\n\r\n        public ");
            
            #line 92 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("InsertCommandBuilder<");
            
            #line 92 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> Insert()\r\n        {\r\n            return new ");
            
            #line 94 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("InsertCommandBuilder<");
            
            #line 94 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">(this);\r\n        }\r\n\r\n        public static async Task<bool> InsertAsync(");
            
            #line 97 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" instance, DbConnection connection) \r\n        {\r\n            return await new ");
            
            #line 99 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("InsertCommandBuilder<");
            
            #line 99 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@">(instance)
                .WithConnection(connection)
                .ExecuteAsync();
        }

        public ");

            #line 105 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));

            #line default
            #line hidden
            this.Write("UpdateCommandBuilder<");

            #line 105 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));

            #line default
            #line hidden
            this.Write(@"> Update()
        {
            return new ");

            #line 108 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));

            #line default
            #line hidden
            this.Write("UpdateCommandBuilder<");

            #line 108 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));

            #line default
            #line hidden
            this.Write(@">(this);
        }

        public static async Task<int> UpdateAsync(");

            #line 112 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));

            #line default
            #line hidden
            this.Write(@" instance, DbConnection connection)
        {
            return await new ");

            #line 115 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));

            #line default
            #line hidden
            this.Write("UpdateCommandBuilder<");

            #line 115 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));

            #line default
            #line hidden
            this.Write(@">(instance)
                .WithConnection(connection)
                .ExecuteAsync();
        }

        public static DeleteCommandBuilder Delete()
        {
            return new DeleteCommandBuilder();
        }

        public class DeleteCommandBuilder : SqlCommandBuilder<DeleteCommandBuilder>
        {
            public DeleteCommandBuilder()
            {
            }

            public async Task<int> ExecuteAsync()
            {
                return 0;
            }
        }

        public class TableQueryBuilder : SqlCommandBuilder<TableQueryBuilder>
        {
            private Expression<Func<");
            
            #line 140 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", object?[]>> _SelectClause;\r\n            private Expression<Func<");
            
            #line 141 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", bool>> _WhereClause;\r\n\r\n            private Expression<Func<");
            
            #line 143 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", object?[]>>? _OrderByClause;\r\n            private bool _OrderByDescending = fal" +
                    "se;\r\n\r\n            private int _Limit = -1;\r\n            private int _Offset = -" +
                    "1;\r\n\r\n            public TableQueryBuilder()\r\n            {\r\n            }\r\n\r\n#i" +
                    "f NET6_0_OR_GREATER\r\n            protected System.Data.Common.DbBatch? _Batch;\r\n" +
                    "\r\n            /// <summary>\r\n            /// Specifies the batch to use for subs" +
                    "equent database operations.\r\n            /// </summary>\r\n            /// <remark" +
                    "s>If <paramref name=\"batch\"/> is <see langword=\"null\"/>, the method attempts to " +
                    "create a new\r\n            /// batch from the current connection or transaction. " +
                    "The batch is used to group multiple database commands for\r\n            /// execu" +
                    "tion as a single unit.</remarks>\r\n            /// <param name=\"batch\">The <see c" +
                    "ref=\"DbBatch\"/> instance to associate with the operation, or <see langword=\"null" +
                    "\"/> to create a new\r\n            /// batch from the current connection or transa" +
                    "ction.</param>\r\n            /// <returns>The current instance with the specified" +
                    " batch applied.</returns>\r\n            /// <exception cref=\"ArgumentNullExceptio" +
                    "n\">Thrown if <paramref name=\"batch\"/> is <see langword=\"null\"/> and neither a co" +
                    "nnection nor a transaction is\r\n            /// specified.</exception>\r\n         " +
                    "   /// <exception cref=\"InvalidOperationException\">Thrown if <paramref name=\"bat" +
                    "ch\"/> is <see langword=\"null\"/> and the provided transaction does not have an\r\n " +
                    "           /// associated <see cref=\"DbConnection\"/>.</exception>\r\n            p" +
                    "ublic TableQueryBuilder WithBatch(DbBatch? batch)\r\n            {\r\n              " +
                    "  if (batch == null)\r\n                {\r\n                    if (_Connection == " +
                    "null && _Transaction == null)\r\n                        throw new ArgumentNullExc" +
                    "eption(nameof(batch), \"If batch is null, either connection or transaction must b" +
                    "e specified!\");\r\n\r\n                    _Batch = _Connection?.CreateBatch() ?? _T" +
                    "ransaction!.Connection?.CreateBatch() ?? throw new InvalidOperationException(\"Th" +
                    "e provided transaction has no DbConnection from which a DbBatch could be created" +
                    "\");\r\n                    _Batch.Transaction = _Transaction;\r\n                }\r\n" +
                    "                else\r\n                    _Batch = batch;\r\n\r\n                ret" +
                    "urn this;\r\n            }\r\n\r\n            /// <summary>\r\n            /// Adds a ne" +
                    "w command to the current batch operation.\r\n            /// </summary>\r\n         " +
                    "   /// <remarks>This method should be called only after a batch has been initial" +
                    "ized using\r\n            /// WithBatch(). Attempting to add to a batch without in" +
                    "itialization will result in an exception.</remarks>\r\n            /// <exception " +
                    "cref=\"InvalidOperationException\">Thrown if no batch has been provided. Call With" +
                    "Batch() before invoking this method.</exception>\r\n            public void AddToB" +
                    "atch()\r\n            {\r\n                if (_Batch == null)\r\n                    " +
                    "throw new InvalidOperationException(\"Cannot add to batch when no DbBatch was pro" +
                    "vided. Please call WithBatch() first.\");\r\n\r\n                var batchCommand = _" +
                    "Batch.CreateBatchCommand();\r\n                _Batch.BatchCommands.Add(batchComma" +
                    "nd);\r\n            }\r\n\r\n            /// <summary>\r\n            /// Adds a new com" +
                    "mand to the current database batch asynchronously.\r\n            /// </summary>\r\n" +
                    "            /// <remarks>This method should be called only after a batch has bee" +
                    "n initialized using\r\n            /// WithBatch(). It is typically used to accumu" +
                    "late multiple commands for execution as a single batch\r\n            /// operatio" +
                    "n.</remarks>\r\n            /// <returns>A task that represents the asynchronous o" +
                    "peration.</returns>\r\n            /// <exception cref=\"InvalidOperationException\"" +
                    ">Thrown if no database batch has been provided. Call WithBatch() before invoking" +
                    " this method.</exception>\r\n            public async Task AddToBatchAsync()\r\n    " +
                    "        {\r\n                if (_Batch == null)\r\n                    throw new In" +
                    "validOperationException(\"Cannot add to batch when no DbBatch was provided. Pleas" +
                    "e call WithBatch() first.\");\r\n\r\n                var batchCommand = _Batch.Create" +
                    "BatchCommand();\r\n                _Batch.BatchCommands.Add(batchCommand);\r\n      " +
                    "      }\r\n#endif\r\n\r\n            /// <summary>\r\n            /// Specifies the colu" +
                    "mns to select when querying the user table.\r\n            /// </summary>\r\n       " +
                    "     /// <remarks>If not called, all columns will be selected by default. This m" +
                    "ethod allows for\r\n            /// projection of only the desired columns, which " +
                    "can improve query performance and reduce data\r\n            /// transfer.</remark" +
                    "s>\r\n            /// <param name=\"select\">An expression that defines which proper" +
                    "ties of the <see cref=\"");
            
            #line 224 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> entity to include in the result set.
            /// The expression should return an array of selected property values.</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance, enabling method chaining.</returns>
            public TableQueryBuilder Select(Expression<Func<");
            
            #line 227 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", object?[]>> select)
            {
                _SelectClause = select;
                return this;
            }

            /// <summary>
            /// Adds a filter condition to the query that determines which users are included based on the specified
            /// predicate.
            /// </summary>
            /// <remarks>Only one filter condition can be set per query builder instance; subsequent calls to
            /// <c>Where</c> will overwrite the previous condition.</remarks>
            /// <param name=""where"">An expression that defines the criteria used to select users. The predicate should return <see
            /// langword=""true""/> for users to include in the results.</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance, enabling method chaining for additional query
            /// configuration.</returns>
            public TableQueryBuilder Where(Expression<Func<");
            
            #line 243 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(", bool>> where)\r\n            {\r\n                _WhereClause = where;\r\n          " +
                    "      return this;\r\n            }\r\n\r\n            /// <summary>\r\n            /// " +
                    "Sets the maximum number of user records to return in the query results.\r\n       " +
                    "     /// </summary>\r\n            /// <param name=\"limit\">The maximum number of u" +
                    "ser records to include in the result set. Must be zero or a positive integer.</p" +
                    "aram>\r\n            /// <exception cref=\"ArgumentOutOfRangeException\">Thrown if t" +
                    "he provided <paramref name=\"limit\"/> is negative.</exception>\r\n            /// <" +
                    "returns>The current <see cref=\"TableQueryBuilder\"/> instance with the limit appl" +
                    "ied.</returns>\r\n            public TableQueryBuilder Limit(int limit)\r\n         " +
                    "   {\r\n                ArgumentOutOfRangeException.ThrowIfNegative(limit);\r\n\r\n   " +
                    "             _Limit = limit;\r\n                return this;\r\n            }\r\n\r\n   " +
                    "         /// <summary>\r\n            /// Sets the number of rows to skip before s" +
                    "tarting to return results from the query.\r\n            /// </summary>\r\n         " +
                    "   /// <remarks>Use this method to implement paging in query results. Calling th" +
                    "is method overwrites\r\n            /// any previously set offset value.</remarks>" +
                    "\r\n            /// <exception cref=\"ArgumentOutOfRangeException\">Thrown if the pr" +
                    "ovided <paramref name=\"offset\"/> is negative.</exception>\r\n            /// <para" +
                    "m name=\"offset\">The number of rows to skip. Must be zero or greater.</param>\r\n  " +
                    "          /// <returns>The current <see cref=\"TableQueryBuilder\"/> instance with" +
                    " the offset applied.</returns>\r\n            public TableQueryBuilder Offset(int " +
                    "offset)\r\n            {\r\n                ArgumentOutOfRangeException.ThrowIfNegat" +
                    "ive(offset);\r\n\r\n                _Offset = offset;\r\n                return this;\r" +
                    "\n            }\r\n\r\n            /// <summary>\r\n            /// Limits the number o" +
                    "f rows returned by the query to the specified maximum.\r\n            /// </summar" +
                    "y>\r\n            /// <remarks>Use this method to restrict the result set to a spe" +
                    "cific number of rows, similar to\r\n            /// the SQL TOP clause. Calling th" +
                    "is method overrides any previous row limit set on the query.</remarks>\r\n        " +
                    "    /// <param name=\"top\">The maximum number of rows to return. Must be greater " +
                    "than zero.</param>\r\n            /// <returns>The current <see cref=\"TableQueryBu" +
                    "ilder\"/> instance with the row limit applied.</returns>\r\n            public Tabl" +
                    "eQueryBuilder Top(int top)\r\n            {\r\n                return Limit(top);\r\n " +
                    "           }\r\n\r\n            /// <summary>\r\n            /// Specifies the orderin" +
                    "g of results for the query using the provided expression.\r\n            /// </sum" +
                    "mary>\r\n            /// <remarks>If multiple properties are specified in the arra" +
                    "y, results will be ordered by each\r\n            /// property in the order they a" +
                    "ppear. This method can be chained with other query builder methods to construct\r" +
                    "\n            /// complex queries.</remarks>\r\n            /// <param name=\"clause" +
                    "\">An expression that defines one or more properties of the <see cref=\"");
            
            #line 297 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> entity to order the results by.
            /// The array elements determine the order of precedence. You can use <see cref=""DB.OrderBy""/> for complex ordering (default will be ASC)</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance with the ordering clause applied.</returns>
            public TableQueryBuilder OrderBy(Expression<Func<");
            
            #line 300 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", object?[]>> clause)
            {
                _OrderByClause = clause;
                return this;
            }

            /// <summary>
            /// Specifies a descending order for the query results based on the provided user properties.
            /// </summary>
            /// <remarks>Call this method to order the query results by one or more user properties in
            /// descending order. This method can be chained with other query builder methods to construct complex
            /// queries.</remarks>
            /// <param name=""clause"">An expression that selects one or more properties of the <see cref=""");
            
            #line 312 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> entity to use for ordering the
            /// results in descending order. You can use <see cref=""DB.OrderBy""/> for complex ordering (default will be DESC)</param>
            /// <returns>The current <see cref=""TableQueryBuilder""/> instance to allow method chaining.</returns>
            public TableQueryBuilder OrderByDesc(Expression<Func<");
            
            #line 315 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@", object?[]>> clause)
            {
                _OrderByClause = clause;
                _OrderByDescending = true;
                return this;
            }

            private ISqlVisitor GetSelectVisitor(ParameterExpression param, GetColumnName getColName, DbCommand command)
            {
                return new ");
            
            #line 324 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("SelectVisitor(param, getColName, command);\r\n            }\r\n\r\n            private " +
                    "ISqlVisitor GetWhereVisitor(ParameterExpression param, GetColumnName getColName," +
                    " DbCommand command)\r\n            {\r\n                return new ");
            
            #line 329 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("WhereVisitor(param, getColName, command);\r\n            }\r\n\r\n            private I" +
                    "SqlVisitor GetOrderByVisitor(ParameterExpression param, GetColumnName getColName" +
                    ", DbCommand command, bool orderByDesc)\r\n            {\r\n                return ne" +
                    "w ");
            
            #line 334 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbEnginePrefix));
            
            #line default
            #line hidden
            this.Write("OrderByVisitor(param, getColName, command, orderByDesc);\r\n            }\r\n\r\n      " +
                    "      public async IAsyncEnumerable<");
            
            #line 337 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@"> ExecuteAsync()
            {
                if (_Batch != null)
                    throw new InvalidOperationException(""Cannot execute command, when DbBatch was provided. Please call AddToBatchAsync()"");
                else if (_Connection == null)
                    throw new InvalidOperationException(""Cannot execute command, when no DbConnection was provided. Please call WithConnection()/WithTransaction() first"");

                if (_Connection.State != System.Data.ConnectionState.Open)
                    await _Connection.OpenAsync();

                var command = _Connection.CreateCommand();
                if (_Transaction != null)
                    command.Transaction = _Transaction;

                Stopwatch watch = Stopwatch.StartNew();
                var parser = new SqlQueryBuilderExpressionParser<");
            
            #line 352 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(">(command, ");
            
            #line 352 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".GetColumnDbName, GetSelectVisitor, GetWhereVisitor, GetOrderByVisitor);\r\n       " +
                    "         parser.Process(");
            
            #line 353 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@".TableName, _SelectClause, _WhereClause, _OrderByClause, _OrderByDescending);
                if (_Limit > 0)
                    parser.AddLimit(_Limit);
                if (_Offset > 0)
                    parser.AddOffset(_Offset);

                command.CommandText = parser.ToString();

                // TODO: Move to ILogger loggin rather than Console.WriteLine
                Console.WriteLine($""[TableQueryBuilder] Executing SQL Query: {command.CommandText} (Prepared in {watch.ElapsedMilliseconds} ms)"");

                using var reader = await command.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    yield return ");
            
            #line 367 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(".ConvertFrom(reader);\r\n                }\r\n            }\r\n        }\r\n        ");
            
            #line 371 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CustomPostClass));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n\r\n#nullable disable\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 377 "D:\Socigy\OpenSource\Socigy.OpenSource.DB\Socigy.OpenSource.DB.SourceGenerator\Templates\TableSyntaxGeneratorTemplate.tt"

	public string Namespace { get; set; }
	public string ClassName { get; set; }
    public string DbEnginePrefix { get; set; }

    public string CustomPreClass { get; set; } = "";
    public string CustomPostClass { get; set; } = "";

    #nullable enable
    public IList<(string SourceName, string TypeName, bool IsPrimaryKey, string? Converter)> Columns { get; set; } = [];
    #nullable disable

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class TableSyntaxGeneratorTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
